"""Add delivery fields to celebrations

Revision ID: aac047a58ea4
Revises:
Create Date: 2026-04-01 10:11:41.358110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aac047a58ea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Celebration Page Updates
    op.add_column('celebration_pages', sa.Column('delivery', sa.Enum('EMAIL', 'PHONE', name='deliverymethod'), nullable=False, server_default='EMAIL'))
    op.add_column('celebration_pages', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('celebration_pages', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_celebration_pages_delivery'), 'celebration_pages', ['delivery'], unique=False)
    op.create_index(op.f('ix_celebration_pages_email'), 'celebration_pages', ['email'], unique=False)
    op.create_index(op.f('ix_celebration_pages_phone'), 'celebration_pages', ['phone'], unique=False)

    # Confess Form updates (Safe changes to existing tables)
    op.create_index(op.f('ix_confess_forms_slug'), 'confess_forms', ['slug'], unique=False)

    # Users updates
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    # NOTE: Legacy tables like 'confession_messages' and 'confession_links' are NOT dropped
    # to avoid data loss, even if they are not in the current models.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_confess_forms_slug'), table_name='confess_forms')
    op.drop_index(op.f('ix_celebration_pages_phone'), table_name='celebration_pages')
    op.drop_index(op.f('ix_celebration_pages_email'), table_name='celebration_pages')
    op.drop_index(op.f('ix_celebration_pages_delivery'), table_name='celebration_pages')
    op.drop_column('celebration_pages', 'phone')
    op.drop_column('celebration_pages', 'email')
    op.drop_column('celebration_pages', 'delivery')
    # ### end Alembic commands ###
